name: IPTV Async Auto Tester Engine

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Run IPTV Async Scraper & Tester
      run: python scraper.py

    - name: Commit and Push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html live.m3u
        # ফাইল পরিবর্তন না হলেও যেন এরর না আসে তার জন্য ট্রিকস যোগ করা হলো
        git diff --quiet && git diff --staged --quiet || (git commit -m "🔄 Live Channel Synced [Async Engine]" && git push)
